// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmhzxwrxxjqgafvtnxfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtaHp4d3J4eGpxZ2FmdnRueGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NTM2NjAsImV4cCI6MjA2MDMyOTY2MH0.2qM0bN1kW-7ye69S3tzPWyoDC8MkiKg4fVvjd1RvzPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);